/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as HeIndexRouteImport } from './routes/he/index'
import { Route as RuIndexRouteImport } from './routes/ru/index'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125AgentSlugRouteImport } from './routes/{-$lang}/$agentSlug'
import { Route as ApiFacebookCallbackRouteImport } from './routes/api/facebook/callback'
import { Route as ApiPublicScoutCronRouteImport } from './routes/api/public/scout-cron'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeIndexRoute = HeIndexRouteImport.update({
  id: '/he/',
  path: '/he/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/ru/',
  path: '/ru/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/{-$lang}/',
  path: '/{-$lang}/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125AgentSlugRoute =
  Char123LangChar125AgentSlugRouteImport.update({
    id: '/{-$lang}/$agentSlug',
    path: '/{-$lang}/$agentSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFacebookCallbackRoute = ApiFacebookCallbackRouteImport.update({
  id: '/api/facebook/callback',
  path: '/api/facebook/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScoutCronRoute = ApiPublicScoutCronRouteImport.update({
  id: '/api/public/scout-cron',
  path: '/api/public/scout-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/{-$lang}/$agentSlug': typeof Char123LangChar125AgentSlugRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
  '/he/': typeof HeIndexRoute
  '/ru/': typeof RuIndexRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/public/scout-cron': typeof ApiPublicScoutCronRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/{-$lang}/$agentSlug': typeof Char123LangChar125AgentSlugRoute
  '/en': typeof EnIndexRoute
  '/fr': typeof FrIndexRoute
  '/he': typeof HeIndexRoute
  '/ru': typeof RuIndexRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/public/scout-cron': typeof ApiPublicScoutCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/{-$lang}/$agentSlug': typeof Char123LangChar125AgentSlugRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
  '/he/': typeof HeIndexRoute
  '/ru/': typeof RuIndexRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/public/scout-cron': typeof ApiPublicScoutCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/account'
    | '/admin'
    | '/{-$lang}/$agentSlug'
    | '/en/'
    | '/fr/'
    | '/he/'
    | '/ru/'
    | '/{-$lang}/'
    | '/api/facebook/callback'
    | '/api/public/scout-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/account'
    | '/admin'
    | '/{-$lang}/$agentSlug'
    | '/en'
    | '/fr'
    | '/he'
    | '/ru'
    | '/{-$lang}'
    | '/api/facebook/callback'
    | '/api/public/scout-cron'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accessibility'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/{-$lang}/$agentSlug'
    | '/en/'
    | '/fr/'
    | '/he/'
    | '/ru/'
    | '/{-$lang}/'
    | '/api/facebook/callback'
    | '/api/public/scout-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  Char123LangChar125AgentSlugRoute: typeof Char123LangChar125AgentSlugRoute
  EnIndexRoute: typeof EnIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  HeIndexRoute: typeof HeIndexRoute
  RuIndexRoute: typeof RuIndexRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  ApiFacebookCallbackRoute: typeof ApiFacebookCallbackRoute
  ApiPublicScoutCronRoute: typeof ApiPublicScoutCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/he/': {
      id: '/he/'
      path: '/he'
      fullPath: '/he/'
      preLoaderRoute: typeof HeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/': {
      id: '/ru/'
      path: '/ru'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/{-$lang}'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/$agentSlug': {
      id: '/{-$lang}/$agentSlug'
      path: '/{-$lang}/$agentSlug'
      fullPath: '/{-$lang}/$agentSlug'
      preLoaderRoute: typeof Char123LangChar125AgentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/callback': {
      id: '/api/facebook/callback'
      path: '/api/facebook/callback'
      fullPath: '/api/facebook/callback'
      preLoaderRoute: typeof ApiFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scout-cron': {
      id: '/api/public/scout-cron'
      path: '/api/public/scout-cron'
      fullPath: '/api/public/scout-cron'
      preLoaderRoute: typeof ApiPublicScoutCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  Char123LangChar125AgentSlugRoute: Char123LangChar125AgentSlugRoute,
  EnIndexRoute: EnIndexRoute,
  FrIndexRoute: FrIndexRoute,
  HeIndexRoute: HeIndexRoute,
  RuIndexRoute: RuIndexRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  ApiFacebookCallbackRoute: ApiFacebookCallbackRoute,
  ApiPublicScoutCronRoute: ApiPublicScoutCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
