/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentSlugRouteImport } from './routes/$agentSlug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAgentSlugRouteImport } from './routes/en/$agentSlug'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as FrAgentSlugRouteImport } from './routes/fr/$agentSlug'
import { Route as RuIndexRouteImport } from './routes/ru/index'
import { Route as RuAgentSlugRouteImport } from './routes/ru/$agentSlug'
import { Route as ApiFacebookCallbackRouteImport } from './routes/api/facebook/callback'
import { Route as ApiPublicScoutCronRouteImport } from './routes/api/public/scout-cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSlugRoute = AgentSlugRouteImport.update({
  id: '/$agentSlug',
  path: '/$agentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAgentSlugRoute = EnAgentSlugRouteImport.update({
  id: '/en/$agentSlug',
  path: '/en/$agentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAgentSlugRoute = FrAgentSlugRouteImport.update({
  id: '/fr/$agentSlug',
  path: '/fr/$agentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/ru/',
  path: '/ru/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuAgentSlugRoute = RuAgentSlugRouteImport.update({
  id: '/ru/$agentSlug',
  path: '/ru/$agentSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookCallbackRoute = ApiFacebookCallbackRouteImport.update({
  id: '/api/facebook/callback',
  path: '/api/facebook/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScoutCronRoute = ApiPublicScoutCronRouteImport.update({
  id: '/api/public/scout-cron',
  path: '/api/public/scout-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$agentSlug': typeof AgentSlugRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/en/$agentSlug': typeof EnAgentSlugRoute
  '/fr/$agentSlug': typeof FrAgentSlugRoute
  '/ru/$agentSlug': typeof RuAgentSlugRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
  '/ru/': typeof RuIndexRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/public/scout-cron': typeof ApiPublicScoutCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$agentSlug': typeof AgentSlugRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/en/$agentSlug': typeof EnAgentSlugRoute
  '/fr/$agentSlug': typeof FrAgentSlugRoute
  '/ru/$agentSlug': typeof RuAgentSlugRoute
  '/en': typeof EnIndexRoute
  '/fr': typeof FrIndexRoute
  '/ru': typeof RuIndexRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/public/scout-cron': typeof ApiPublicScoutCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$agentSlug': typeof AgentSlugRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/en/$agentSlug': typeof EnAgentSlugRoute
  '/fr/$agentSlug': typeof FrAgentSlugRoute
  '/ru/$agentSlug': typeof RuAgentSlugRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
  '/ru/': typeof RuIndexRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/public/scout-cron': typeof ApiPublicScoutCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$agentSlug'
    | '/accessibility'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/account'
    | '/admin'
    | '/en/$agentSlug'
    | '/fr/$agentSlug'
    | '/ru/$agentSlug'
    | '/en/'
    | '/fr/'
    | '/ru/'
    | '/api/facebook/callback'
    | '/api/public/scout-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$agentSlug'
    | '/accessibility'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/account'
    | '/admin'
    | '/en/$agentSlug'
    | '/fr/$agentSlug'
    | '/ru/$agentSlug'
    | '/en'
    | '/fr'
    | '/ru'
    | '/api/facebook/callback'
    | '/api/public/scout-cron'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$agentSlug'
    | '/accessibility'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/en/$agentSlug'
    | '/fr/$agentSlug'
    | '/ru/$agentSlug'
    | '/en/'
    | '/fr/'
    | '/ru/'
    | '/api/facebook/callback'
    | '/api/public/scout-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgentSlugRoute: typeof AgentSlugRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EnAgentSlugRoute: typeof EnAgentSlugRoute
  FrAgentSlugRoute: typeof FrAgentSlugRoute
  RuAgentSlugRoute: typeof RuAgentSlugRoute
  EnIndexRoute: typeof EnIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  RuIndexRoute: typeof RuIndexRoute
  ApiFacebookCallbackRoute: typeof ApiFacebookCallbackRoute
  ApiPublicScoutCronRoute: typeof ApiPublicScoutCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$agentSlug': {
      id: '/$agentSlug'
      path: '/$agentSlug'
      fullPath: '/$agentSlug'
      preLoaderRoute: typeof AgentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/$agentSlug': {
      id: '/en/$agentSlug'
      path: '/en/$agentSlug'
      fullPath: '/en/$agentSlug'
      preLoaderRoute: typeof EnAgentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/$agentSlug': {
      id: '/fr/$agentSlug'
      path: '/fr/$agentSlug'
      fullPath: '/fr/$agentSlug'
      preLoaderRoute: typeof FrAgentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/': {
      id: '/ru/'
      path: '/ru'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/$agentSlug': {
      id: '/ru/$agentSlug'
      path: '/ru/$agentSlug'
      fullPath: '/ru/$agentSlug'
      preLoaderRoute: typeof RuAgentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/callback': {
      id: '/api/facebook/callback'
      path: '/api/facebook/callback'
      fullPath: '/api/facebook/callback'
      preLoaderRoute: typeof ApiFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scout-cron': {
      id: '/api/public/scout-cron'
      path: '/api/public/scout-cron'
      fullPath: '/api/public/scout-cron'
      preLoaderRoute: typeof ApiPublicScoutCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgentSlugRoute: AgentSlugRoute,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EnAgentSlugRoute: EnAgentSlugRoute,
  FrAgentSlugRoute: FrAgentSlugRoute,
  RuAgentSlugRoute: RuAgentSlugRoute,
  EnIndexRoute: EnIndexRoute,
  FrIndexRoute: FrIndexRoute,
  RuIndexRoute: RuIndexRoute,
  ApiFacebookCallbackRoute: ApiFacebookCallbackRoute,
  ApiPublicScoutCronRoute: ApiPublicScoutCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
